// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"
	"time"
)

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"pt-20 pb-9\"><div class=\"max-w-[1240px] mx-auto px-5\"><div class=\"flex flex-col md:flex-row justify-between gap-12 pb-15 border-b border-[#14532d]/10\"><div class=\"max-w-xs\"><a href=\"#\" class=\"flex items-center gap-2.5 text-[#14532d] font-extrabold text-lg tracking-tight\"><img src=\"https://59doenkwa7.ufs.sh/f/jhH9iucglD1p5YFUtmYpg6eLHpOUzn1suTKhxQ3yvBRaES50\" alt=\"Zoie Foundation Logo\" class=\"w-8 h-8 rounded-full object-cover shrink-0\"> Zoie Foundation</a><p class=\"mt-4 text-[#62675d] text-sm leading-relaxed\">Feeding communities, one street at a time.</p></div><div class=\"flex flex-wrap gap-12 md:gap-20\"><div><h4 class=\"text-xs font-extrabold uppercase tracking-widest text-[#f97316] mb-4\">Contact</h4><ul class=\"space-y-2 text-sm text-[#62675d]\"><li>zoefoundationfts@gmail.com</li><li>+234 813 538 7714</li></ul></div><div><h4 class=\"text-xs font-extrabold uppercase tracking-widest text-[#f97316] mb-4\">Follow</h4><ul class=\"space-y-2 text-sm text-[#62675d]\"><li><a href=\"https://www.instagram.com/zoie_foundation_fts?utm_source=ig_web_button_share_sheet&stkn=ZDNlZDc0MzIxNw==\" class=\"hover:text-[#14532d] transition-colors\">Instagram</a></li><li><a href=\"#\" class=\"hover:text-[#14532d] transition-colors\">X (Twitter)</a></li></ul></div></div></div><div class=\"pt-7 flex flex-col sm:flex-row justify-between text-xs text-[#62675d] gap-2\"><span>© ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.Itoa(time.Now().Year()))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/footer.templ`, Line: 46, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " Zoie Foundation. All rights reserved.</span> <span>Made for impact.</span></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
