// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"fixed top-0 inset-x-0 z-50 transition-colors duration-300\" _=\"on scroll from window if window.scrollY > 40 add .nav-scrolled to me else remove .nav-scrolled from me\"><nav class=\"max-w-6xl mx-auto px-4 sm:px-5 py-3.5 flex items-center justify-between\"><!-- Brand Logo + Text --><a href=\"#top\" class=\"flex items-center gap-2 shrink-0 group\"><img src=\"https://59doenkwa7.ufs.sh/f/jhH9iucglD1p5YFUtmYpg6eLHpOUzn1suTKhxQ3yvBRaES50\" alt=\"Zoie Foundation Logo\" class=\"w-7 h-7 sm:w-8 sm:h-8 rounded-full object-cover shrink-0 border border-white/20 group-hover:scale-105 transition-transform duration-200\"><div class=\"flex items-center gap-1 text-base sm:text-lg font-extrabold tracking-tight leading-none\"><span class=\"text-white\">Zoie</span> <span class=\"text-orange-400\">Foundation</span></div></a><!-- Desktop Nav Links --><div class=\"hidden md:flex items-center gap-6 lg:gap-8 text-sm font-medium text-white/85\"><a href=\"#about\" class=\"hover:text-orange-300 transition\">About</a> <a href=\"#feed-the-street\" class=\"hover:text-orange-300 transition\">Feed The Street</a> <a href=\"#gallery\" class=\"hover:text-orange-300 transition\">Gallery</a> <a href=\"#donate\" class=\"hover:text-orange-300 transition\">Donate</a></div><!-- CTA Button --><a href=\"#donate\" class=\"inline-flex items-center rounded-full bg-orange-600 px-4 sm:px-5 py-2 sm:py-2.5 text-xs sm:text-sm font-semibold text-white shadow-lg shadow-orange-600/30 hover:bg-orange-700 hover:-translate-y-0.5 transition shrink-0\">Donate Now</a></nav></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
